[build]
  command = "npm run build"  # Build command
  publish = "public/"        # Folder where the build will be published

[build.environment]
  NODE_VERSION = "16"        # Set the Node.js version to match your local environment

[[plugins]]
  package = "@netlify/plugin-lighthouse"  # Lighthouse plugin for build insights
